List questions screen
AGES-PUCRS/simulados-front-admin pull request #7
Opened 2018-10-23 13:54 UTC by guidraghetti

2018-10-23 14:34 UTC, renanpvaz requested changes
Acho que é importante cuidar para não criarmos PRs tão grandes. Neste caso por exemplo, não entendi o porquê da tela de edição estar sendo adicionada junto se o PR se chama "List questions screen"

2018-10-23 14:34 UTC, renanpvaz commented on src/components/Sidebar/index.js
> +    path: '/questoesPendentes',
Acho que deveria ser separado por traços já que é da URL: /questoes-pendentes

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/EditQuestion/index.js
> +      options: [
Acho que simplificaria bastante o código e daria menos trabalho lidar com propriedades distintas (optionA, optionB, etc) em vez de uma lista.

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/EditQuestion/index.js
> +    const { question } = this.props.location.state
Esta não é a forma ideal de usar [parâmetros com o react router](https://reacttraining.com/react-router/web/example/url-params). O parâmetro precisa ser declarado nas rotas e ele será injetado como prop pelo router.

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/EditQuestion/index.js
> +const mapStateToProps = state => ({
Assumindo que a alteração do parâmetro seja feita, aqui você poderá acessar um segundo argumento (normalmente nomeado ownProps) onde poderá acessar o id da questão. Obtendo o id da questão vindo da url, neste caso, seguindo a convenção, o ideal seria passá-lo para o selector de alternativas (ou um novo selector) como argumento e usá-lo para filtrar as mesmas.

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/EditQuestion/index.js
> +    const { alternatives } = this.props
Como evidenciei noutro comentário, essa lógica deveria ser responsabilidade de um selector. Além disso, props recebidas controladas pelo redux não deveriam ser armazenadas e gerenciadas no estado local de componentes.

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/EditQuestion/index.js
> +            onChange={event => this.setState({ statement: event.target.value })}
A atualização dos campos pode ser simplificada, normalmente em forms usamos um único método para atualizar qualquer campo. Este método usa as propriedades `name` (que deve ser igual ao nome da propriedade) e `value`, acessadas de `event.target` (elemento do dom que disparou o evento [no caso o input]), para setar o valor.

[Um exemplo aqui](https://github.com/AGES-PUCRS/simulados-front-admin/blob/dev/src/scenes/CreateQuestion/index.js#L29).

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/EditQuestion/index.js
> +  render() {
Por padrão o render é sempre o último dos métodos.

2018-10-23 14:34 UTC, renanpvaz commented on src/components/AvailableQuestions/index.js
> +export default connect(
Este componente é chamado de funcional, burro, presentacional, etc, portanto não deveria saber da existência do redux. O ideal é usarmos o connect apenas em scenes e containers, este componente deveria apenas receber as props passadas "na mão" para ele.

2018-10-23 14:34 UTC, renanpvaz commented on src/components/AvailableQuestions/index.js
> +      onClick={() => props.push('/edit', { question })}
Não é necessário usar o push aqui, basta importar o <Link> de react-router-dom e envolver o card nele.

2018-10-23 14:34 UTC, renanpvaz commented on src/components/AvailableQuestions/index.js
> +        <Moment format="DD/MM/YYYY">{question.created_at}</Moment>
Acho que não precisamos de moment.js (que é tão pesado) para um caso tão simples. Acho que o seguinte deve resolver:
```
created_at.toLocaleDateString()
// ou (não sei o formato)
new Date(created_at).toLocaleDateString()
```
Se ainda assim quiserem ter uma biblioteca de datas, sugiro usar a date-fns.
Para outros casos:
[You Dont Need Momentjs](https://github.com/you-dont-need/You-Dont-Need-Momentjs)

2018-10-23 14:34 UTC, renanpvaz commented on src/scenes/ListQuestions/index.js
> +          {!!questions ? (
Quando não houverem questões esse valor não vai ser um array vazio? Se for o caso seria melhor verificar questions.length

2018-11-01 00:35 UTC, guidraghetti commented on src/scenes/EditQuestion/index.js
> +      options: [
Infelizmente não temos como ajustar esse pois o backEnd nos retorna um array com todas as questões e outro array com todas  as alternativas. Sendo assim temos que verificar no frontEnd quais alternativas pertencem a questão.

2018-11-10 00:26 UTC, guidraghetti commented on src/scenes/EditQuestion/index.js
> +            onChange={event => this.setState({ statement: event.target.value })}
Tentamos refatorar dessa maneira, porém o método não atualiza o campo com as novas informações.

2018-11-17 00:18 UTC, merged